### ISSUE TITLE
Mure stuff: Deprecate `handler`, then long live `destination`

### ISSUE THREAD

**Issue by tabulon** [perlancar/perl-Getopt-Long-More#21]
## The WHAT

_Deprecate_ the term `handler` in favor of the term `destination`.

This includes all mention in documentation, parameter/attribute names, as well as in the source code; except what is strictly needed for documenting and handling the _deprecation_ itself.

The  _deprecation cycle_ should last no more than **1 year**; considering the current estimate of relatively low number of GLM users.

## The WHY

At this time, [Getopt::Long] (**GoL**) documentation just talks about `destination` to refer to pretty much the same thing as GLM's `handler`.

Since [Getopt::Long::More] (**GLM**) aims and claims to be a fully compatible _drop-in replacement_ for **GoL**, it's only normal that it would employ the same names that **GoL** uses for the same things --if, of course, those really _are_ the same things; which happen to be the case here.

Also, the term `destination` has the advantage of having been around at least since the 1970s, without evolving much in its semi-ambiguous (but well established) conventional meaning of _"where stuff ends up"_, which is exactly the concept sought here.

Apart from the points raised above, the term `handler` is probably not that suitable in any case, since it is usually understood to only denote  `CODE`; whereas in this case, `destination` could be just about any kind of reference (`SCALAR`, `ARRAY`, `HASH`, and God knows what else, in addition to `CODE`).

So, in a little while, we'll hopefully be able to shout :

`handler`is _deprecated_, long live `destination`!

For current users of GLM, that may come to be a bit _awkward_, at first; and for those who have been using only for `CODE`, it might just sound simply outrageous; but later on, things should settle just fine.

*****

## About "MURE STUFF"

This is hopefully one of the rare [Mure stuff][wiki_mure] series (Note the "u" :-).

[Mure stuff][wiki_mure] are NOT _[More stuff]_, in the sense that they won't be bringing new features / added value, at least in the immediate outset.

Instead, [Mure stuff][wiki_mure] are basically stuff that we want to somehow come back to; in order to harmonize / reorganize/ rationalize / limit / ...

When you set out for that kind of thing, you often end up _renaming_ and/or _deprecating_ stuff as well...

So, in general, it's not that much fun to deal with [Mure stuff][wiki_mure], but sometimes, _"you gotta do what you gotta do"._

********

See the [wiki][wiki_mure] for "more" on [Mure stuff][wiki_mure], where you will also find some ["fun read"][wiki_mure] as well.

---

[wiki_mure]: https://github.com/tabulon-ext/perl-Getopt-Long-More/wiki/%22Mure-stuff%22
[Getopt::Long]: https://metacpan.org/pod/Getopt::Long
[Getopt::Long::Descriptive]: https://metacpan.org/pod/Getopt::Long::Descriptive
[Getopt::Long::More]: https://metacpan.org/pod/Getopt::Long::More

**Comment by perlancar** [comment]
I'm marking #21 as closed (all merged)
